services:
    terminal42_html_injection.html_injector:
        class: Terminal42\HtmlInjectionBundle\HtmlInjector
        arguments:
            - "@contao.framework"

    terminal42_html_injection.listener.html_injection:
        class: Terminal42\HtmlInjectionBundle\EventListener\HtmlInjectionListener
        arguments:
            - "@terminal42_html_injection.html_injector"
